---
- name: Auto-hide the dock
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
    value: "false"
    state: present

- name: Dock Position on screen
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
    value: "'BOTTOM'"
    state: present
