---
# for os: Ubuntu
- name: Auto-hide the dock
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
    value: "false"
    state: present

- name: Dock Position on screen
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
    value: "'BOTTOM'"
    state: present

# Configure dock behavior
- name: Show Volumes and Devices
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/show-mounts"
    value: "false"
    state: present

- name: Show Trash
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/show-trash"
    value: "false"
    state: present
